// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProvaBlogdoAGITest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT01BotoLupapresente() {
    driver.get("https://blogdoagi.com.br/");
    driver.manage().window().setSize(new Dimension(1382, 736));
    {
      List<WebElement> elements = driver.findElements(By.id("search-open"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void cT02BotoPesquisarpresente() {
    driver.get("https://blogdoagi.com.br/");
    driver.manage().window().setSize(new Dimension(1382, 736));
    driver.findElement(By.id("search-open")).click();
    try {
      Thread.sleep(/);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".desktop-search .search-submit"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void cT03TextBoxPesquisarpresente() {
    driver.get("https://blogdoagi.com.br/");
    driver.manage().window().setSize(new Dimension(1382, 736));
    driver.findElement(By.id("search-open")).click();
    try {
      Thread.sleep(/);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".desktop-search .search-submit"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void cT04BotoBuscarTextopresente() {
    driver.get("https://blogdoagi.com.br/");
    driver.manage().window().setSize(new Dimension(1382, 736));
    driver.findElement(By.id("search-open")).click();
    driver.findElement(By.name("s")).click();
    driver.findElement(By.name("s")).sendKeys("agibank");
    driver.findElement(By.cssSelector(".desktop-search .search-submit")).click();
    assertThat(driver.findElement(By.cssSelector(".archive-title > span")).getText(), is("agibank"));
  }
  @Test
  public void cT05TextBoxPesquisarinvisvelfuncionalidadeesconder() {
    driver.get("https://blogdoagi.com.br/");
    driver.manage().window().setSize(new Dimension(1382, 736));
    driver.findElement(By.id("search-open")).click();
    try {
      Thread.sleep(/);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.id("search-open")).click();
    try {
      Thread.sleep(/);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector(".desktop-search .search-submit")));
    }
  }
  @Test
  public void cT06BotoBuscarTextoinvisvelfuncionalidadeesconder() {
    driver.get("https://blogdoagi.com.br/");
    driver.manage().window().setSize(new Dimension(1382, 736));
    driver.findElement(By.id("search-open")).click();
    try {
      Thread.sleep(/);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.id("search-open")).click();
    try {
      Thread.sleep(/);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector(".desktop-search .search-submit")));
    }
  }
}
